version: '3.8'

services:
  juan-note-mcp:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: juan-note-mcp
    restart: unless-stopped

    # Network configuration for localhost access
    network_mode: host

    # Environment variables
    environment:
      - NODE_ENV=production
      - MCP_PORT=3000
      - JUAN_NOTE_HOST=localhost
      - JUAN_NOTE_PORT=1420

    # Security
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp

    # Resource limits
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'

    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('health check')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Logging
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

# Alternative configuration for bridge networking (if host networking is not preferred)
# networks:
#   default:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.20.0.0/16